include:
  - board: xiao_ble//zmk
    shield: around_forty_db_right rgbled_adapter
    artifact-name: around_forty_db_right
    snippet: studio-rpc-usb-uart
  - board: xiao_ble//zmk
    shield: around_forty_db_left rgbled_adapter
    artifact-name: around_forty_db_left
  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: settings_reset
